name = "MLOptm"
uuid = "b1aa900e-b14c-4154-9286-9942520b9516"
authors = ["Moaz El-Essawey"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
